### ISSUE TITLE
Prefer yarn for npm/package.json client

### ISSUE THREAD

**Issue by ayumi** [brave/sync#1]
[yarn](https://yarnpkg.com/) is a drop-in replacement for `npm` with bonuses:
- Deterministic
- Package checksums
- Package requests retried on failure
- Faster

### What it means to "Prefer yarn":
- When working on sync, devs will install and add packages with `yarn install` and `yarn add {package}`. This keeps `yarn.lock` up to date.

@diracdeltas

**Comment by diracdeltas** [comment]
sgtm
