### ISSUE TITLE
Change to Parent bookmark folder on Android is not sycned to laptop or iOS device

### ISSUE THREAD

**Issue by LaurenWags** [brave/sync#107]
Did you search for similar issues before submitting this one?
Yes

Description:
Changing the parent folder of a bookmarks folder does not sync to laptop, but does sync android-android.

Pyramid 0 is Mac Laptop
Pyramid 1 is Nexus 5
Pyramid 2 is Galaxy S4

Device Details:

Install Type(ARM, x86): Arm
Device(Phone, Tablet, Phablet): Mac Laptop, Nexus5, Galaxy S4
Android Version: Nexus 5 is 5.1, Galaxy S4 is 5.0.1

Brave Version:
Android version is 1.0.23beta
Laptop version is 0.17.2

Steps to reproduce:
0. Laptop and both Androids do not have any bookmarks (clean installs)
1. Create sync group on mac laptop
2. Join sync group - joined on Android devices 1&2 (nexus and galaxy respectively)
3. On device 1 (Nexus), create a bookmark at ‘Mobile Bookmarks’ level, create a folder which contains 2 different bookmarks.
4. Folder and all bookmarks are synced to laptop and android device 2
5. On device 1 (nexus), create a new folder as the parent folder for the folder created in step 3 (To do this - open bookmarks, tap on 3 dots on the folder, select edit, tap on mobile bookmarks, tap on new folder, put name, select checkmark in upper right corner, nav back to bookmarks).
6. Change is synced to laptop and android device 2
7. Back on device 1, change the parent bookmark. (to do this: open bookmarks again, tap on folder created in step 5, tap on 3 dots for the sub folder (this is the folder which was created in step 3). select edit. change the parent folder to be mobile bookmarks instead of the folder created in step 5. nav back to bookmarks.)
8. The parent folder change is synced to android device 2, but not to laptop.

Actual Behavior
Laptop still displays:
Folder from Step 5 > Folder from Step 3 > 2 bookmarks created in step 3.

Expected Behavior
Laptop should reflect the change in bookmark parent folder.

Is this an issue with Beta build?
Yes

Is this an issue in the currently released version?
No

Can this issue be consistently reproduced?
Yes

Extra QA steps:
1. Repeat steps 2-8 with an iOS device. Parent folder change from Android is not updated on iOS device either.
2.
3.

Website problems only:

did you check with Brave Shields down?
did you check in Chrome for same behavior?

Screenshot if needed:
Laptop (incorrect folder structure):
screen shot 2017-06-14 at 4 25 30 pm

Nexus 5 and Galaxy S4 (correct folder structure):
screenshot_2017-06-14-16-25-15

Any related issues:

**Comment by diracdeltas** [comment]
here's what is sent/received when the two devices are both browser-laptop:

# device 1:

create folder:
sending record: {"action":1,"bookmark":{"isFolder":true,"site":{"creationTime":0,"customTitle":"folder 1","favicon":"","lastAccessedTime":0,"location":""}},"deviceId":{"0":2},"objectId":{"0":168,"1":90,"2":119,"3":21,"4":9,"5":125,"6":69,"7":96,"8":2,"9":71,"10":143,"11":126,"12":227,"13":94,"14":79,"15":107}}

create and move bookmark 1:
sending record: {"action":1,"bookmark":{"isFolder":false,"site":{"creationTime":0,"customTitle":"","favicon":"","lastAccessedTime":1498769794171,"location":"http://example.com/","title":"Example Domain"}},"deviceId":{"0":2},"objectId":{"0":245,"1":128,"2":134,"3":38,"4":219,"5":56,"6":207,"7":150,"8":175,"9":58,"10":207,"11":87,"12":87,"13":60,"14":148,"15":38}}
sending record: {"action":1,"bookmark":{"isFolder":false,"parentFolderObjectId":{"0":168,"1":90,"2":119,"3":21,"4":9,"5":125,"6":69,"7":96,"8":2,"9":71,"10":143,"11":126,"12":227,"13":94,"14":79,"15":107},"site":{"creationTime":0,"customTitle":"","favicon":"","lastAccessedTime":1498769794171,"location":"http://example.com/","title":"Example Domain"}},"deviceId":{"0":2},"objectId":{"0":245,"1":128,"2":134,"3":38,"4":219,"5":56,"6":207,"7":150,"8":175,"9":58,"10":207,"11":87,"12":87,"13":60,"14":148,"15":38}}

create and move bookmark 2:
sending record: {"action":1,"bookmark":{"isFolder":false,"site":{"creationTime":0,"customTitle":"","favicon":"https://www.google.com/images/branding/product/ico/googleg_lodp.ico","lastAccessedTime":1498769826838,"location":"https://www.google.com/","title":"Google"}},"deviceId":{"0":2},"objectId":{"0":91,"1":97,"2":252,"3":2,"4":59,"5":0,"6":29,"7":12,"8":240,"9":55,"10":28,"11":127,"12":174,"13":133,"14":35,"15":34}}
sending record: {"action":1,"bookmark":{"isFolder":false,"parentFolderObjectId":{"0":168,"1":90,"2":119,"3":21,"4":9,"5":125,"6":69,"7":96,"8":2,"9":71,"10":143,"11":126,"12":227,"13":94,"14":79,"15":107},"site":{"creationTime":0,"customTitle":"","favicon":"https://www.google.com/images/branding/product/ico/googleg_lodp.ico","lastAccessedTime":1498769826838,"location":"https://www.google.com/","title":"Google"}},"deviceId":{"0":2},"objectId":{"0":91,"1":97,"2":252,"3":2,"4":59,"5":0,"6":29,"7":12,"8":240,"9":55,"10":28,"11":127,"12":174,"13":133,"14":35,"15":34}}


# device 2:

receiving bookmarks:
got 4 decrypted records in BOOKMARKS after 1498769772
getting existing objects for 4 BOOKMARKS
resolved 4 BOOKMARKS -> 2

this is the records object received by RESOLVED_SYNC_RECORDS:
[{"action":0,"bookmark":{"isFolder":false,"parentFolderObjectId":[168,90,119,21,9,125,69,96,2,71,143,126,227,94,79,107],"site":{"creationTime":0,"customTitle":"","favicon":"","lastAccessedTime":1498769794171,"location":"http://example.com/","title":"Example Domain"}},"deviceId":[2],"objectData":"bookmark","objectId":[245,128,134,38,219,56,207,150,175,58,207,87,87,60,148,38],"syncTimestamp":1498769802745},{"action":0,"bookmark":{"isFolder":false,"parentFolderObjectId":[168,90,119,21,9,125,69,96,2,71,143,126,227,94,79,107],"site":{"creationTime":0,"customTitle":"","favicon":"https://www.google.com/images/branding/product/ico/googleg_lodp.ico","lastAccessedTime":1498769826838,"location":"https://www.google.com/","title":"Google"}},"deviceId":[2],"objectData":"bookmark","objectId":[91,97,252,2,59,0,29,12,240,55,28,127,174,133,35,34],"syncTimestamp":1498769831824}]


# device 1:

create a new folder, move 'folder 1' into this folder:
sending record: {"action":1,"bookmark":{"isFolder":true,"site":{"creationTime":0,"customTitle":"folder 2","favicon":"","lastAccessedTime":0,"location":""}},"deviceId":{"0":2},"objectId":{"0":151,"1":37,"2":201,"3":36,"4":187,"5":156,"6":99,"7":148,"8":168,"9":88,"10":3,"11":13,"12":163,"13":81,"14":151,"15":167}}
sending record: {"action":1,"bookmark":{"isFolder":true,"parentFolderObjectId":{"0":151,"1":37,"2":201,"3":36,"4":187,"5":156,"6":99,"7":148,"8":168,"9":88,"10":3,"11":13,"12":163,"13":81,"14":151,"15":167},"site":{"creationTime":0,"customTitle":"folder 1","favicon":"","lastAccessedTime":0,"location":"","title":""}},"deviceId":{"0":2},"objectId":{"0":168,"1":90,"2":119,"3":21,"4":9,"5":125,"6":69,"7":96,"8":2,"9":71,"10":143,"11":126,"12":227,"13":94,"14":79,"15":107}}


# device 2:

receiving bookmarks:
got 2 decrypted records in BOOKMARKS after 1498770073
getting existing objects for 2 BOOKMARKS
resolved 2 BOOKMARKS -> 2

this is the records object received by RESOLVED_SYNC_RECORDS:
[{"action":0,"bookmark":{"isFolder":true,"site":{"creationTime":0,"customTitle":"folder 2","favicon":"","lastAccessedTime":0,"location":"","title":""}},"deviceId":[2],"objectData":"bookmark","objectId":[151,37,201,36,187,156,99,148,168,88,3,13,163,81,151,167],"syncTimestamp":1498770091141},{"action":1,"bookmark":{"isFolder":true,"parentFolderObjectId":[151,37,201,36,187,156,99,148,168,88,3,13,163,81,151,167],"site":{"creationTime":0,"customTitle":"folder 1","favicon":"","lastAccessedTime":0,"location":"","title":""}},"deviceId":[2],"objectData":"bookmark","objectId":[168,90,119,21,9,125,69,96,2,71,143,126,227,94,79,107],"syncTimestamp":1498770096808}]


# device 1:

change parent folder of 'folder 1' back to the original (top level):
sending record: {"action":1,"bookmark":{"isFolder":true,"site":{"creationTime":0,"customTitle":"folder 1","favicon":"","lastAccessedTime":0,"location":"","title":""}},"deviceId":{"0":2},"objectId":{"0":168,"1":90,"2":119,"3":21,"4":9,"5":125,"6":69,"7":96,"8":2,"9":71,"10":143,"11":126,"12":227,"13":94,"14":79,"15":107}}


# device 2:

receiving bookmarks:
got 1 decrypted records in BOOKMARKS after 1498770373
getting existing objects for 1 BOOKMARKS
resolved 1 BOOKMARKS -> 1

this is the records object received by RESOLVED_SYNC_RECORDS:
[{"action":1,"bookmark":{"isFolder":true,"site":{"creationTime":0,"customTitle":"folder 1","favicon":"","lastAccessedTime":0,"location":"","title":""}},"deviceId":[2],"objectData":"bookmark","objectId":[168,90,119,21,9,125,69,96,2,71,143,126,227,94,79,107],"syncTimestamp":1498770393581}]

**Comment by SergeyZhukovsky** [comment]
The problem is still exist.
