### ISSUE TITLE
Editing bookmark name on laptop is not propagated to Android

### ISSUE THREAD

**Issue by srirambv** [brave/sync#119]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Editing bookmark name on laptop is not propagated to Android

- Platform (Win7, 8, 10? macOS? Linux distro?):
Pyramid 0 - Laptop 
Pyramid 1 - Android

- Brave Version (revision SHA):
Pyramid 0 - Laptop (0.17.4)
Pyramid 1 - Android (1.0.24)

- Steps to reproduce:
    1. Sync Android with laptop with QR code
    2. Import bookmarks on laptop with nested bookmark folder
    3. Edit any nested folder name on Android, changes propagate to laptop
    4. Edit any nested folder name on laptop, changes are not propagate to Android
    
- Actual result:
Editing bookmark name on laptop is not propagated to Android

- Expected result:
Change propagation should be bi-directional

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/27391823-e0775c92-569c-11e7-9b2e-884cdfab3109.png)
![image](https://user-images.githubusercontent.com/17010094/27391870-fc9d88a6-569c-11e7-9b69-a4f0a58619f3.png)

- Any related issues:
#111

**Comment by diracdeltas** [comment]
could you re-try with latest 0.17.x? if it's broken there, please try master @srirambv

**Comment by ayumi** [comment]
@srirambv we did a sync lib update recently; is this issue still happening? cc @SergeyZhukovsky

**Comment by srirambv** [comment]
Verified works fine with 0.17.14 and 1.0.24 Android
