### ISSUE TITLE
Allow pause and resume of pending sync uploads

### ISSUE THREAD

**Issue by ayumi** [brave/sync#125]
When uploading sync records, a browser needs to remain online. If the browser exits then any pending sync uploads will be lost. This is okay for small numbers of records, but initial sync sends all bookmarks and could take many minutes (for 1000s of bookmarks).

If the browser is closed during initial sync, it should persist pending records and resume upload when reopened.

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/28077611-26e27460-665a-11e7-9837-3552347fb6a8.png)


Fetch fails if one of the connected device is offline
![image](https://user-images.githubusercontent.com/17010094/28077661-4cb405fa-665a-11e7-8962-703f44bc55be.png)

**Comment by ayumi** [comment]
@srirambv sorry, can you clarify the issue you're seeing? (and if it appears even when devices all return online)

The message "Ignoring record" might happen normally when a browser client downloads its own records.

**Comment by srirambv** [comment]
When one or both devices in the sync group are offline the records are not sent.  Here's the steps that I followed

Pyramid 0 - Windows 10 x64 (Laptop)
Pyramid 1 - Ubuntu x64 VM

1. Setup Sync on Pyramid 0
2. Sync Pyramid 1 with code words
3. Import bookmarks file(more than 3k records) in Pyramid 1
4. Once sync records started showing up disconnected internet on the laptop (so both devices are offline)
5. Connect back to internet sync completed both devices have the imported bookmarks folder (pyramid 0.json shared on slack)
6. Disconnect VM and add a bookmark(in this case it was `about:preference`) , Record not synced on Pyramid 0 (screenshot 1 in the above reply) when VM is connected back to internet
7. Disconnect VM again, add a new bookmark in pyramid 0 (this time it was #107 ), bookmark not synced when VM is back online (screenshot 2 in the above reply)

So if one of the device is offline then records are not dropped.

**Comment by ayumi** [comment]
@srirambv thanks for that really good STR!

I tried the STR and saw records aren't sent. However I restarted the Pyramids and all records were sent and received correctly.

Pending records are only reuploaded during sync init, which usually happens when you restart the browser. We don't handle connects/disconnects as they happen but maybe we can add that.

**Comment by srirambv** [comment]
>However I restarted the Pyramids and all records were sent and received correctly. 

So the user has to manually restart the browser every time the device is offline?? I feel the device connectivity has to be handled, as closing the browser deletes the tab history and would be a high impact if we ask users to restart the browser in order for the sync to complete.

>Pending records are only reuploaded during sync init, which usually happens when you restart the browser.  

Could this init be triggered when there is a disconnect? That way when it reconnects the pending records are automatically sent across!
