### ISSUE TITLE
Empty folder is not synced after 'Sync this device' is re-enbled

### ISSUE THREAD

**Issue by LaurenWags** [brave/sync#134]
Did you search for similar issues before submitting this one?
Yes

Description:
When sync is not on (i.e. 'Sync this device' is off in Preferences), if an empty folder is added, the folder is not sycned when 'Sync this device' is turned on.

Pyramid 0 is Mac Laptop
Pyramid 1 is Nexus 5

Device Details:

Install Type(ARM, x86): Arm
Device(Phone, Tablet, Phablet): Mac Laptop, Nexus5
Android Version: Nexus 5 is 5.1

Brave Version:
Android version is 1.0.24beta
Laptop version is 0.17.15

Steps to reproduce:
1. Have laptop and Android synced successfully.
2. On laptop go to Preferences > Sync.
3. Toggle off 'Sync this device'.
4.  On laptop, add an empty bookmark folder.
5. Wait a few minutes, and then toggle on 'Sync this device'.

Actual Behavior
empty folder isn't synced to Android.

Expected Behavior
empty folder should be synced.

Is this an issue in the currently released version?

Can this issue be consistently reproduced?
Yes

Extra QA steps:

Website problems only:

did you check with Brave Shields down?
did you check in Chrome for same behavior?

Screenshot if needed:

Any related issues:

**Comment by ayumi** [comment]
I repro'd this between 2 browser-laptop pyramids (62f69f139e5e386d863be3ffba98414c95a291b1, MacOS).

Bookmark sent; bookmark folder did not.
