### ISSUE TITLE
Allow self-hosting ?

### ISSUE THREAD

**Issue by farfeduc** [brave/sync#155]
Hi,

I would like to know if you would like to make this part of brave self-hostable ?

If yes, I think the best way to do it would be to offer the possibility to use Minio as a AWS-like backend : https://docs.minio.io/docs/how-to-use-aws-sdk-for-javascript-with-minio-server

I think this would be great. To configure you could simply use an environment variable to specify the Minio/AWS endpoint like `AWS_ENDPOINT`.

It would also be great to have a Dockerfile and docker-compose.yml files to easily run your own sync instance.

I hope you would like to go in this direction. I can provide some help to add those to the current repo if you don't have the time.

**Comment by diracdeltas** [comment]
We definitely want to allow self hosting eventually though it's not on the roadmap yet. cc @ayumi 

As a first pass, we could have the sync server be configurable for people who are building the sync library themselves and running Brave in dev mode.

**Comment by diracdeltas** [comment]
we should move discussion to https://github.com/brave/sync/issues/58
