### ISSUE TITLE
Bookmarks sync to wrong folder (Other bookmarks to Mobile bookmarks)

### ISSUE THREAD

**Issue by m-cote** [brave/sync#312]
**Description:**
When syncing desktop bookmarks with android bookmarks all bookmarks from folders 'Bookmarks bar' and 'Other bookmarks' get synced to folder 'Mobile bookmarks' on Android.

**Platform:**

- Desktop: Linux
OS: Solus x86_64
Kernel: 5.0.7-114.current

- Mobile: Android 8.0.0

**Brave Version (revision SHA):**
- Desktop: Version 0.63.48 Chromium: 74.0.3729.108 (Official Build)
- Mobile: Brave 1.0.92, Chromium 73.0.3683.90

**Steps to reproduce:**

1. In desktop browser: create some bookmarks in the folder 'Bookmarks bar' and in the folder 'Other bookmarks'. 
![Screenshot from 2019-05-09 21-07-20](https://user-images.githubusercontent.com/7547394/57478959-f7da6980-72a4-11e9-8d4a-86d951e55ea8.png)
In android browser there are no bookmarks.
![photo_2019-05-09_22-10-01](https://user-images.githubusercontent.com/7547394/57480079-7cc68280-72a7-11e9-9c33-e1e62097ad82.jpg)

2. Enable sync.

**Actual result:**
![photo_2019-05-09_22-09-41](https://user-images.githubusercontent.com/7547394/57480131-91a31600-72a7-11e9-977c-09624ba36fe8.jpg)
![photo_2019-05-09_22-09-55](https://user-images.githubusercontent.com/7547394/57480135-94057000-72a7-11e9-99a0-9f8ea203e3b7.jpg)

All desktop bookmarks from folders 'Bookmarks bar' and 'Other bookmarks' were saved to 'Mobile bookmarks' folder.

**Expected result:**
![photo_2019-05-09_22-15-46](https://user-images.githubusercontent.com/7547394/57480354-2574e200-72a8-11e9-9e78-d815a21d1e2d.jpg)
All desktop bookmarks from folder 'Bookmarks bar' to be saved in 'Bookmarks bar' folder on Android. All desktop bookmarks from folder 'Other bookmarks' to be saved in 'Other bookmarks' folder on Android.

**Comment by darkdh** [comment]
@m-cote thanks for reporting. This issue will be addressed in https://github.com/brave/brave-browser/issues/5158
