### ISSUE TITLE
Confirm sync code does nothing

### ISSUE THREAD

**Issue by MRVDH** [brave/sync#321]
I have two laptops and one phone. I set up a sync chain on laptop 1, then added my phone with the sync code. This worked. I then tried to add laptop 2 and this is the result.

No console logs, no errors, nothing.
The code you see in this picture is different from my actual code for privacy reasons.
![gif](https://i.imgur.com/IxuSYfe.gif)

**Comment by diracdeltas** [comment]
@MRVDH since this is a desktop issue, please open it in https://github.com/brave/brave-browser. thanks!

**Comment by MRVDH** [comment]
Sorry, didn't know that! Done!
