### ISSUE TITLE
npm package for brave-sync

### ISSUE THREAD

**Issue by garvankeeley** [brave/sync#33]
Currently on iOS I am using npm to manage dependent packages.
For reference, this is how my package.json looks now
```
{
  "name": "brave",
  "dependencies": {
    "ad-block": "2.0.0",
    "node-gyp": "^3.2.1",
    "tracking-protection": "1.1.5"
  }
}
```
To avoid another dependency management system, it would rock if I could add brave-sync to this.

**Comment by diracdeltas** [comment]
would it be sufficient to just wrap the `main` function of client/sync.js (https://github.com/brave/sync/blob/staging/client/sync.js#L139-L182) in a `module.exports`, add a package.json for it, and publish to NPM? or do you need something more sophisticated?

**Comment by garvankeeley** [comment]
Would be good to have similar to:
`node <nameOfTestWrapper>.js login ./path` and if creds are in `path` use them, if not create them.
Also, have argument to that js to perform standalone test cases for syncing and run the sync lib through its functionality in terms of storing data, resolving conflicts.
I think resolving conflict tests would require simulating multiple devices syncing with that script.

**Comment by garvankeeley** [comment]
I think my above comment applies more to issue #34, I thought we were on that bug. Is that question about the wrapped `main` related more to issue #34?

Regarding your packaging question:
I am looking to being able to grab the npm package, npm install && npm run build to generate a browserfied js file I run in a webview. Not having published npm packages myself, I am not the best to comment on minimal vs. fancy approaches

**Comment by diracdeltas** [comment]
> I am looking to being able to grab the npm package, npm install && npm run build to generate a browserfied js file I run in a webview. Not having published npm packages myself, I am not the best to comment on minimal vs. fancy approaches

That is actually what I thought this issue was referring to. If so, I can take it.

**Comment by diracdeltas** [comment]
@garvankeeley though it's worth mentioning, you can simply download the pre-built browserified js file using:

`curl -L -o $SYNC_PATH $(curl -s https://api.github.com/repos/brave/sync/releases/latest | grep \/bundle.js | head -n 1 | cut -d '"' -f 4)`

where `$SYNC_PATH` is the filesystem location for the browserified js file. this is actually what browser-laptop is doing. is that better, or do you prefer npm?

**Comment by garvankeeley** [comment]
I can do that or use carthage, the iOS dependancy manager. This bug is a nice-to-have for consistency since npm is what is being used for brave-related dependencies. I can roll with what I have, it isn't blocking in any way.

**Comment by diracdeltas** [comment]
adding this to pyramid 2 because it's needed to make sure that the release has the correct version of sync

**Comment by diracdeltas** [comment]
on second thought, https://github.com/brave/sync/issues/128 is more useful for pyramid 2

**Comment by diracdeltas** [comment]
closing in favor of https://github.com/brave/sync/issues/199
