### ISSUE TITLE
Enable running brave-sync using node

### ISSUE THREAD

**Issue by garvankeeley** [brave/sync#34]
Followup from #33, it would be amazing if brave-sync was runnable (unit-testable) using node.

This would provide clearer units (i.e. minimal functions) for me to implement, and also form a point of reference as a known good state. 

Right now, when I am running into problems, I have too many points of failure/unknowns on iOS (thoughts such as: did I setup the code wrong, am I not calling code correctly on iOS, etc.). I could just compare what I am doing against running it on the command-line, and eliminate various possibilities that way.

**Comment by ayumi** [comment]
We currently unit test most client code except client/sync.js, the library - browser client interface. Is that the part you'd like to have tested?

**Comment by garvankeeley** [comment]
If I could run this on the command-line to login/init, then also on the command-line do some sync operations with a test data set, that would be sweet.
If I need a functional reference point, I want to avoid having to build brave browser and debug in that to compare how sync works in there to iOS (for instance if I am trying to find an implementation bug in iOS).
It isn't so much unit testing. It would be the ability to run it stand-alone in some form (which seems like a form of unit test for this lib).

**Comment by diracdeltas** [comment]
right now this is kind of tricky because `client/sync.js` depends on a bunch of `window` methods that are not natively available in node. if this is a blocker for you, i can make the client code fully isomorphic.

**Comment by garvankeeley** [comment]
No, not a blocker. Is there plans to make the sync lib stand-alone testable? If so, I could wait for that. It will be much easier to have something I can easily compare against and experiment with while I am implementing.

**Comment by diracdeltas** [comment]
> Is there plans to make the sync lib stand-alone testable

It is already testable in a window environment, see `npm run browsertest' for instance. we did not have plans to make it testable via command-line node, but that is doable. i am not sure how useful that would be for you since the node JS environment is probably very different from the iOS webview JS environment

**Comment by garvankeeley** [comment]
cool i'll take  a look at `browsertest`

> since the node JS environment is probably very different from the iOS webview JS environment

Agreed, I would think that switching back and forth between a lightweight known-good test env and iOS code will ease implementation. It can help to point in the right direction as to source of a problem.

**Comment by diracdeltas** [comment]
Closing this unless further action is needed
