### ISSUE TITLE
show list of devices

### ISSUE THREAD

**Issue by diracdeltas** [brave/sync#41]
brave/browser-laptop should display the list of sync devices and have a button to remove each of them

**Comment by ayumi** [comment]
1. To show sync devices, I'm imagining a Sync library IPC endpoint which will go through Preferences and return the Device records. Can I work on that?

2. How do you delete a device? You could add a Delete Device record, which would express "I'm trying to delete my other device" but would that prevent the deleted device from syncing records?

Or maybe it would also go thru all Records and delete all records written by the deleted device.

**Comment by diracdeltas** [comment]
> To show sync devices, I'm imagining a Sync library IPC endpoint which will go through Preferences and return the Device records. Can I work on that?

sgtm. you can use the subroutine from maybeSetDeviceId, which gets existing device IDs from Preferences.

> How do you delete a device? You could add a Delete Device record, which would express "I'm trying to delete my other device" but would that prevent the deleted device from syncing records?

maybe:
1. if deleting this device, then send a DELETE SyncRecord with objectData device ('name' can be anything)
2. if deleting another device, create a new SyncRecord with `objectData` field that is `DeletedDevice`? Then the next time the deleted device syncs, it sees itself in DeletedDevice and does step 1.

alternatively we could just say that devices can only delete themselves or delete all devices (by deleting the user or preferences)

> Or maybe it would also go thru all Records and delete all records written by the deleted device.

i think i would still expect that the device doesn't keep syncing stuff when it's on
