### ISSUE TITLE
Sync bookmark order

### ISSUE THREAD

**Issue by ayumi** [brave/sync#45]
Right now syncing bookmarks to a new device disrupts the ordering from the original device. This is surprising.

Most users would expect that upon Syncing a new pyramid, bookmarks sync with original ordering.

**Comment by ayumi** [comment]
Partially implemented by https://github.com/brave/sync/commit/2953593c734c63f1b569cfca2a00b7fe5d8d128e with the addition of SyncRecord.Bookmark.index

**Comment by diracdeltas** [comment]
closed by https://github.com/brave/browser-laptop/commit/620cffc21681b49e08df05a9ae33bbbe1075ab27
