### ISSUE TITLE
sync extension needs pyramid icon

### ISSUE THREAD

**Issue by ayumi** [brave/sync#52]
expected
![screen shot 2017-02-06 at 16 25 20](https://cloud.githubusercontent.com/assets/521861/22773785/d9d8dc46-ee58-11e6-8f63-d5c2d942bc8b.png)

icons:
![sync-16](https://cloud.githubusercontent.com/assets/521861/22773839/1fee68b8-ee59-11e6-85ab-e3e204d349bd.png)
![sync-48](https://cloud.githubusercontent.com/assets/521861/22773838/1fedf298-ee59-11e6-8bc4-35e96d40ab2b.png)
![sync-128](https://cloud.githubusercontent.com/assets/521861/22773837/1fedab4e-ee59-11e6-8dae-25c013acde3c.png)

**Comment by diracdeltas** [comment]
logo at https://github.com/brave/sync/wiki/Design would be sweet too

**Comment by diracdeltas** [comment]
fixed by ed176a6210767e2147bb97c0b17feeff3a90a6f4 in browser-laptop feature/syncing
