### ISSUE TITLE
Sync browser settings

### ISSUE THREAD

**Issue by mrose17** [brave/sync#59]
could i also start syncing

- general settings 
- search settings
- tab settings
- security settings
- - private data settings (the 7 on/off switches)
- - password IF i have selected the Brave built-in password manager
- - autofill settings, full screen content, DNT, plugin, widevine, saved sit permissions
- - shield settings (excluding saved site exceptions for the ledger)
- advanced settings

yes, i'm asking for everything other than the ledger! and not *zoom* either!

**Comment by cwmke** [comment]
I would request zoom not be synced since different devices need different levels of zoom.

**Comment by mrose17** [comment]
@cwmke - _excellent_ point... i agree!

**Comment by lukemulks** [comment]
@mrose17 is the Brave Wallet backup included in the Sync data? Could be valuable for users that locally save this, in cases where they have hardware failure that kills the local disk. 

I think it would be really cool for the user to be able to Sync their Brave Stat counts across devices: 

- Trackers Blocked
- Ads Blocked
- HTTPS Upgrades
- Est. Time Saved

If Brave stats traveled with the user, they would paint a more real-world picture of Brave protection (especially as mobile Sync comes online). 

Invokes an emotional connection to Brave, as we are attributing unified decentralized value to an accurate accounting of the global protection of the user. We care enough to care, and care even more not to directly know.

Also would help as a failover in cases like the ones I've experienced on Windows where my stat counts have been wiped in the past. That's a bummer when it happens.

**Comment by mrose17** [comment]
@yan & @ayumi - your thoughts?

**Comment by ndaidong** [comment]
+1 for syncing password.

**Comment by srirambv** [comment]
+1 for syncing password from community https://community.brave.com/t/sync-passwords-across-devices-in-addition-to-existing-data/9382/2

**Comment by ismay** [comment]
This would be great. Syncing just the settings that can be applied to all versions of brave (regardless of device) would allow for way simpler installs on new devices. Brave already cuts down on install time by natively having an adblock, https everywhere, but this would improve it even more.

**Comment by quentinsf** [comment]
+1 for syncing - bookmarks, history and passwords

**Comment by gruvin** [comment]
+1 for syncing password the MOST important thing for sync. Should have been the FIRST thing it did Gosh. On Mac, the iCloud keychain should be used, please.

**Comment by hh-here** [comment]
More than a year after this item was opened and we are STILL waiting for some way to sync the passwords. 
How are we meant to move/copy/sync when we change distributions etc...
Can the saved passwords be copied to the 'new' location & opened/used?
If so (poor-man's-sync), where are they?
If not, why not?

**Comment by mrose17** [comment]
OBE

**Comment by ckujau** [comment]
_"Order of the British Empire"_? _"Overcome by events"_? If the latter, that would be really unfortunate. I too planned on switching from [Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Firefox_Sync "Firefox Sync") to Brave and its [design document](https://github.com/brave/sync/wiki/Design) at least wanted to have:

 `Data to sync: bookmarks, history, site settings, list of devices. User chooses collections to sync.`

It would be very unfortunate if "bookmarks" would be the only sync element for the [forseeable future](https://github.com/brave/browser-android-tabs/issues/137#issuecomment-344958760 "Implement sync feature #137"). I know, I know..."patches welcome"...I'm not complaining, merely stating a missing feature. Or is there a tracking bug for future sync items that I missed? Thanks.

**Comment by gruvin** [comment]
@ckujau Brave dropped Firefox code has been home based for some time now. It does EVERYTHING Chrome does, as if it were Chrome. That includes password syncing etc. :-)

THIS ISSUE NEEDS TO BE CLOSED

**Comment by bsclifton** [comment]
@ckujau this issue in particular was closed a while ago (early 2018)- before we moved (on Desktop) from the Muon version of the browser to the newer Brave Core

I think we have issues capturing what we'd like synced in a few places, in case you wanted to give it a thumbs up or add a comment:
- [Sync browser settings](https://github.com/brave/sync/issues/223)
- [Sync ad/tracker blocked statistics](https://github.com/brave/brave-browser/issues/3460)
(I swear there were more; I couldn't find them)

Of course, you're also welcome to create an issue in our Desktop repo with what you've like to see captured:
https://github.com/brave/brave-browser/issues

**Comment by gruvin** [comment]
@bsclifton Nice Thanks :-)

**Comment by ckujau** [comment]
Using Brave v0.61.36 (Beta) here and `brave://sync` only shows "Bookmarks" to sync. If the comment above suggests to login to a Google Account to sync the rest, then I could just use Google Chrome instead of Brave, no? But yeah, I shall take this to the support sites or another tracker, indeed.

**Comment by rmonsurate** [comment]
> Using Brave v0.61.36 (Beta) here and `brave://sync` only shows "Bookmarks" to sync. If the comment above suggests to login to a Google Account to sync the rest, then I could just use Google Chrome instead of Brave, no? But yeah, I shall take this to the support sites or another tracker, indeed.

Agreed. We need to be able to sync passwords securely between desktop and mobile.

**Comment by FelschR** [comment]
Syncing extensions & perhaps installed PWAs would also be nice.

**Comment by Mercurial** [comment]
password sync please!

**Comment by Dario82** [comment]
password sync please!

**Comment by diogomax** [comment]
+1 for password syncing

**Comment by protoman** [comment]
Sync between desktop and mobile is very important. While in desktop it is easier to type some long passwords, in mobild like Androidm it is really hard, so keeping the passwords in sync would be very useful.

**Comment by CoVoCre** [comment]
Should we create a new issue or should they re open this one ???
I also discovered brave, and was eager to test the innovative secure sync only getting data on my devices and no servers... But wait, it's only options are to sync bookmarks :
<img width="656" alt="Capture d’écran 2019-06-28 à 00 14 50" src="https://user-images.githubusercontent.com/25605953/60304433-c6435d80-9939-11e9-8b9b-faf756717ee3.png">
 So, how can I sign in to my google account for the browser @ckujau ? I don't see that option (although yes it's not ideal, it would be better for me than just using chrome) !

**Comment by CoVoCre** [comment]
Oooho check out #288 !!! A new issue is already open, at least for passwords !
