### ISSUE TITLE
Blank device name for sync'd Android device

### ISSUE THREAD

**Issue by lukemulks** [brave/sync#80]
I was able to successfully sync my Android phone with browser-laptop :-) 

I noticed that in the Sync panel in browser-laptop, the device name for my Android device was blank: 

![brave-android-sync-devicename-04192017](https://cloud.githubusercontent.com/assets/8979240/25205521/e665d5b8-2517-11e7-8037-6415d5506f0d.PNG)

When I check in the Android Sync options, it doesn't appear that I'm able to assign a name for the device in the same way that I'm able to on browser-laptop. 

I'm not able to assign a name from the Sync panel in browser-laptop either. 

This may already be a ToDo for Android, but wanted to note in case it wasn't. 

I'm not sure if the same thing is happening for iOS devices either, but may be worth checking out.

**Comment by SergeyZhukovsky** [comment]
@lukemulks yup it is a problem on Android side. I'm going to work on that soon.

**Comment by alexwykoff** [comment]
This is implemented now.
